---
abstract: 'Retrieve list of filesystems and their properties'
author:
  - 'Nicola Worthington <nicolaw@cpan.org>'
  - 'Jens Rehsack <rehsack@cpan.org>'
build_requires:
  Test::More: '0.9'
configure_requires:
  Carp: '0'
  Cwd: '0'
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  FindBin: '0'
  IO: '0'
  IPC::Cmd: '0.80'
  Module::Pluggable: '4.8'
  Params::Util: '1.00'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.141170'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Sys-Filesystem
no_index:
  directory:
    - t
    - inc
recommends:
  perl: '5.018001'
requires:
  Carp: '0'
  Cwd: '0'
  File::Spec: '0'
  FindBin: '0'
  IO: '0'
  IPC::Cmd: '0.80'
  Module::Pluggable: '4.8'
  Params::Util: '1.00'
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Sys-Filesystem
  homepage: https://metacpan.org/release/Sys-Filesystem
  repository: https://github.com/rehsack/Sys-Filesystem
version: '1.406'
