---
abstract: 'Retrieve list of filesystems and their properties'
author:
  - 'Nicola Worthington <nicolaw@cpan.org>'
  - 'Jens Rehsack <rehsack@cpan.org>'
build_requires:
  Test::More: 0.9
configure_requires:
  Carp: 0
  ExtUtils::MakeMaker: 0
  FindBin: 0
  IO: 0
  IPC::Cmd: 0.80
  Module::Pluggable: 4.8
  Params::Util: 1.00
  perl: 5.008001
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.8, CPAN::Meta::Converter version 2.132830'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sys-Filesystem
no_index:
  directory:
    - t
    - inc
recommends:
  perl: 5.018001
requires:
  Carp: 0
  FindBin: 0
  IO: 0
  IPC::Cmd: 0.80
  Module::Pluggable: 4.8
  Params::Util: 1.00
  perl: 5.008001
resources:
  license: http://www.apache.org/licenses/LICENSE-2.0.html
version: 1.405
